version: '3.8'

services:
  backend:
    build: .
    ports:
      - 3140:8000
    restart: unless-stopped
    pull_policy: always
    # Optional healthcheck
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s